# Generated by Django 4.1.3 on 2022-12-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_brand_cart_category_product_trendingproduct_slider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
